# -*- coding: utf-8 -*-
"""P1HW2_MitchellAshley.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14-s4S1-ej6210bdMKWsRFhjjp3P8TeAP
"""

# Ashley Mitchell
# 2/11/2025
# P1HW2
# Using print and input functions

print("This program calculates and displays travel expenses ")
print()

budget = int(input("Enter budget: "))
print()
travel_destination = input("Enter travel your destination: ")
print()
gas = int(input("How much do you think you will spend on gas? "))
print()
accomm_hotel = int(input("Approximately, how much will you need for accommodation/hotel? "))
print()
food = int(input("Last, how much do you need for food? "))
print()
new_balance = budget - (gas + accomm_hotel + food)
print()

print("------------Travel Expenses------------")
print("Location: ", travel_destination)
print("Initial Budget: ", budget)
print()
print("Fuel: ", gas)
print("Accommodation: ", accomm_hotel)
print("Food: ", food)
print()
print("Remaining Balance: ", new_balance)