# -*- coding: utf-8 -*-
"""P1HW1_MitchellAshley.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XPSrpquwsufw9Sh7Srzg30MQW-CvCI5I
"""

# Ashley Mitchell
# 2/10/2025
# P1HW1
# Using input and print functions

print("-----Calculating Exponents-----")

print()
print()

base_value = int(input("Enter an integer as the base value: "))
expo_value = int(input("Enter an integer as the exponent: "))
value = base_value ** expo_value

print()
print()

print(base_value, "raised to the power of", expo_value, "is",value, "!!")

print()
print()

print("-----Addition and Subtraction-----")

print()
print()

start_int = int(input("Enter a starting integer: "))
add_int = int(input("Enter an integer to add: "))
sub_int = int(input("Enter an integer to subtract: "))
total = start_int + add_int - sub_int

print()
print()

print(start_int, "+", add_int, "-", sub_int, "is equal to", total)