# -*- coding: utf-8 -*-
"""P2HW1_MitchellAshley.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GaNvOqzSsbXC8WJlpl-lxLQm3ATfv601
"""

# Ashley Mitchell
# 2/26/2025
# P2HW1
# Using print, input functions and string formatting

print("This program calculates and displays travel expenses ")
print()

budget = int(input("Enter budget: "))
print()
travel_destination = input("Enter travel your destination: ")
print()
gas = int(input("How much do you think you will spend on gas? "))
print()
accomm_hotel = int(input("Approximately, how much will you need for accommodation/hotel? "))
print()
food = int(input("Last, how much do you need for food? "))
print()
new_balance = budget - (gas + accomm_hotel + food)

print("------------Travel Expenses------------")
print(f"{'Location:':<20}", travel_destination)
print(f"{'Initial Budget:':<20} ${budget:.2f}")
print(f"{'Fuel:':<20} ${gas:.2f}")
print(f"{'Accommodation:':<20} ${accomm_hotel:.2f}")
print(f"{'Food:':<20} ${food:.2f}")
print("--"*20)
print()
print(f"{'Remaining Balance:':<20} ${new_balance:.2f}")