# -*- coding: utf-8 -*-
"""P2LAB1_MitchellAshley.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18MqSAYaDoCR0x1V8okoY7G0tUt209fO5
"""

# Ashley Mitchell
# 2/17/2025
# P2LAB1
# Using formatting output

import math

# Get the radius from the user as a float
radius = float(input("What is the radius of the circle? "))
print()

# Calculate diameter
diameter = 2 * radius

# Calculate circumference
circum = 2 * math.pi * radius

# Calculate area
area = math.pi * radius ** 2

# Display values to user
print(f"The diameter of the circle is {diameter:.1f}")
print()
print(f"The circumference of the circle is {circum:.2f}")
print()
print(f"The area of the circle is {area:.3f}")